apiVersion: v1
kind: Pod
metadata:
  name: flask-app
  labels:
    app: flask
spec:
  containers:
  - name: flask
    image: 152410580623.dkr.ecr.us-east-1.amazonaws.com/shuklev-flask-repo:latest
    ports:
    - containerPort: 5000
