apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "db-secret"
spec:
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  refreshInterval: 10m
  target:
    name: db-secret
  dataFrom:
  - extract:
      key: db_credtwo
