apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "ingress"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: acme-issuer-{{ .Values.deployment.env }}
spec:
  rules:
    {{- if eq .Values.deployment.env "prod" }}
    - host: "vaklinov.online"
      {{- else }}
    - host: "{{ .Values.deployment.env }}.vaklinov.online"
      {{ end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.deployment.name }}"
                port:
                  number: {{ .Values.deployment.port }}
  tls:
    - hosts:
      {{- if eq .Values.deployment.env "prod" }}
      - "vaklinov.online"
      {{- else }}
      - "{{ .Values.deployment.env }}.vaklinov.online"
      {{ end }} 
      secretName: myingress-cert
