apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: "{{ .Values.deployment.env }}-aws-secretsmanager"
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
       jwt:
          serviceAccountRef:
            name: external-secret
            namespace: kube-system