apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "env-secret"
spec:
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  refreshInterval: 1m
  target:
    name: "devops-secret6"
  dataFrom:
  - extract:
      key: devops-secret6
