pipeline {
    agent any

    environment {
        REPO = "252803719446.dkr.ecr.us-east-2.amazonaws.com/test-repo"
    }
    stages {
        stage('Pull source') {
            steps {
                git branch: 'feature/devOps_lyubo_jenkins', credentialsId: 'lyubo', url: 'git@github.com:nvaklinov/flask-project.git'
            }
        }
        stage('Build') {
            steps {
		sh "pwd && ls -al"
		sh "ls -al env/"
                sh "env/build.sh"
            }
        }
	stage('deploy') {
            steps {
                sh "env/deploy.sh"
            }
        }
    }
    post {
        always {
	    /* Use slackNotifier.groovy from shared library and provide current build result as parameter */
            slackNotifier(currentBuild.currentResult)
            cleanWs()
        }
    }
}
