pipeline {
    agent any
    environment {
        REPO = "252803719446.dkr.ecr.us-east-2.amazonaws.com/test-repo"
    }
    stages {
        stage('Pull source') {
            steps {
                git branch: 'origin/feature/devOps_lyubo_jenkins', credentialsId: 'lyubo', url: 'git@github.com:nvaklinov/flask-project.git'
            }
        }
        stage('Build') {
            steps {
                sh "env/docker build -t ${env.REPO}:latest"
            }
        }
        stage('Deploy') {
            steps {
                sh "deploy.sh"
            }
        }
    }
    post {
        always {
            slackNotifier(currentBuild.currentResults)
            cleanWs()
        }
    }
}
