pipeline {
    agent any

    environment {
        REPO = "252803719446.dkr.ecr.us-east-2.amazonaws.com/test-repo"
    }
    stages {
        stage('Pull source') {
            steps {
                git branch: 'feature/devOps_lyubo_jenkins', credentialsId: 'lyubo', url: 'git@github.com:nvaklinov/flask-project.git'
            }
        }
        stage('Build') {
            steps {
		sh "../build.sh"
            }
        }
        stage('Deploy') {
            steps {
                sh "deploy.sh"
            }
        }
    }
}
