name: Build and Deploy

on:
  push:
    branches:
       - dev

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: ecr login
         env:
            AWS_ACCESS_KEY_ID: ${{secrets.ACCESS_KEY}}
            AWS_SECRET_ACCESS_KEY: ${{secrets.SECRET_KEY}}
            AWS_DEFAULT_REGION: "eu-central-1"
         run: |
           aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 058302395964.dkr.ecr.eu-central-1.amazonaws.com
       - name: build
         run: |
           docker build -t "058302395964.dkr.ecr.eu-central-1.amazonaws.com/nikdevops:${{ github.sha }}" .
       - name: test
         run: |
           docker run -dit -p 5000:5000 058302395964.dkr.ecr.eu-central-1.amazonaws.com/nikdevops:${{ github.sha }}
           sleep 5
           curl http://localhost:5000 && echo "tests are succesfull" || echo "tests failed"
       - name: push
         run: |
           docker push 058302395964.dkr.ecr.eu-central-1.amazonaws.com/nikdevops:${{ github.sha }}
       - name: deploy
         env:
            AWS_ACCESS_KEY_ID: ${{secrets.ACCESS_KEY}}
            AWS_SECRET_ACCESS_KEY: ${{secrets.SECRET_KEY}}
            AWS_DEFAULT_REGION: "eu-central-1"
         run: |
           aws eks update-kubeconfig --name nikdevops-cluster --region $AWS_DEFAULT_REGION
           helm upgrade flask helm/ --install --wait --create-namespace --namespace dev --atomic --set deployment.tag=${{ github.sha }} --set deployment.env=dev